In [2]:
import mlx.core as mx

In [62]:
x = mx.arange(12)

In [64]:
x

array([0, 1, 2, ..., 9, 10, 11], dtype=int32)

In [65]:
x.shape

[12]

In [66]:
x.size

12

In [67]:
X = x.reshape(3, 4)

In [68]:
X

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 10, 11]], dtype=int32)

In [69]:
mx.zeros((2, 3, 4))

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],
       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=float32)

In [71]:
mx.ones((2, 3, 4))

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],
       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=float32)

In [72]:
mx.random.normal([3, 4])

array([[0.950684, 1.97247, -0.767013, -0.15761],
       [-1.07589, -0.661559, -1.00611, 0.948475],
       [-0.704848, -0.185356, -0.795145, 1.40381]], dtype=float32)

In [74]:
mx.array([[2, 1, 4, 2],
          [1, 2, 3, 4],
          [4, 3, 2, 1]])

array([[2, 1, 4, 2],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)

In [75]:
X[-1], X[1:3]

(array([8, 9, 10, 11], dtype=int32),
 array([[4, 5, 6, 7],
        [8, 9, 10, 11]], dtype=int32))

In [76]:
X[1, 2] = 17
X

array([[0, 1, 2, 3],
       [4, 5, 17, 7],
       [8, 9, 10, 11]], dtype=int32)

In [77]:
X[:2, :] = 12
X

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [8, 9, 10, 11]], dtype=int32)

In [78]:
mx.exp(x)

array([1, 2.71828, 7.38906, ..., 8103.08, 22026.5, 59874.1], dtype=float32)

In [22]:
x = mx.array([1.0, 2, 4, 8])
y = mx.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(array([3, 4, 6, 10], dtype=float32),
 array([-1, 0, 2, 6], dtype=float32),
 array([2, 4, 8, 16], dtype=float32),
 array([0.5, 1, 2, 4], dtype=float32),
 array([1, 4, 16, 64], dtype=float32))

In [59]:
X = mx.arange(12, dtype=mx.float32).reshape((3,4))
Y = mx.array([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
mx.concatenate((X, Y), axis=0), mx.concatenate((X, Y), axis=1)

(array([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
        [2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=float32),
 array([[0, 1, 2, ..., 1, 4, 3],
        [4, 5, 6, ..., 2, 3, 4],
        [8, 9, 10, ..., 3, 2, 1]], dtype=float32))

In [25]:
X == Y

array([[false, true, false, true],
       [false, false, false, false],
       [false, false, false, false]], dtype=bool)

In [26]:
X.sum()

array(66, dtype=float32)

In [27]:
a = mx.arange(3).reshape((3, 1))
b = mx.arange(2).reshape((1, 2))
a, b

(array([[0],
        [1],
        [2]], dtype=int32),
 array([[0, 1]], dtype=int32))

In [28]:
a + b

array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)

In [29]:
X[-1], X[1: 3]

(array([8, 9, 10, 11], dtype=float32),
 array([[4, 5, 6, 7],
        [8, 9, 10, 11]], dtype=float32))

In [30]:
X[1, 2] = 9
X

array([[0, 1, 2, 3],
       [4, 5, 9, 7],
       [8, 9, 10, 11]], dtype=float32)

In [32]:
X[0:2, :] = 12
X

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [8, 9, 10, 11]], dtype=float32)

In [33]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [34]:
Z = mx.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4616361072
id(Z): 4616361072


In [36]:
before = id(X)
Y += X
id(X) == before

True

In [37]:
import numpy

In [38]:
A = numpy.array(X)
B = mx.array(A)
type(A), type(B)

(numpy.ndarray, mlx.core.array)

In [40]:
a = numpy.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)