In [1]:
import mlx.core as mx

In [2]:
x = mx.array(3.0)
y = mx.array(2.0)

x + y, x * y, x / y, x**y

(array(5, dtype=float32),
 array(6, dtype=float32),
 array(1.5, dtype=float32),
 array(9, dtype=float32))

In [3]:
x = mx.arange(4)
x

array([0, 1, 2, 3], dtype=int32)

In [4]:
x[3]

array(3, dtype=int32)

In [5]:
len(x)

4

In [6]:
x.shape

[4]

In [8]:
A = mx.arange(20).reshape(5, 4)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)

In [9]:
A.T

array([[0, 4, 8, 12, 16],
       [1, 5, 9, 13, 17],
       [2, 6, 10, 14, 18],
       [3, 7, 11, 15, 19]], dtype=int32)

In [10]:
B = mx.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)

In [11]:
B == B.T

array([[true, true, true],
       [true, true, true],
       [true, true, true]], dtype=bool)

In [12]:
X = mx.arange(24).reshape(2, 3, 4)
X

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]],
       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)

In [35]:
A = mx.arange(6, dtype=mx.float32).reshape(2, 3)
B = A
A, A+B

(array([[0, 1, 2],
        [3, 4, 5]], dtype=float32),
 array([[0, 2, 4],
        [6, 8, 10]], dtype=float32))

In [36]:
A * B

array([[0, 1, 4],
       [9, 16, 25]], dtype=float32)

In [37]:
a = 2
X = mx.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(array([[[2, 3, 4, 5],
         [6, 7, 8, 9],
         [10, 11, 12, 13]],
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]], dtype=int32),
 [2, 3, 4])

In [38]:
x = mx.arange(3, dtype=mx.float32)
x, x.sum()

(array([0, 1, 2], dtype=float32), array(3, dtype=float32))

In [39]:
A.shape, A.sum()

([2, 3], array(15, dtype=float32))

In [40]:
A.shape, A.sum(axis=0).shape

([2, 3], [3])

In [41]:
A.shape, A.sum(axis=1).shape

([2, 3], [2])

In [42]:
A.sum(axis=[0, 1]) == A.sum()

array(true, dtype=bool)

In [45]:
A.mean(), A.sum() / A.size

(array(2.5, dtype=float32), array(2.5, dtype=float32))

In [46]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(array([1.5, 2.5, 3.5], dtype=float32), array([1.5, 2.5, 3.5], dtype=float32))

In [47]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(array([[3],
        [12]], dtype=float32),
 [2, 1])

In [48]:
A / sum_A

array([[0, 0.333333, 0.666667],
       [0.25, 0.333333, 0.416667]], dtype=float32)

In [49]:
A.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]], dtype=float32)

In [52]:
y = mx.ones(3, dtype=mx.float32)
x, y, mx.tensordot(x, y, dims=1)

(array([0, 1, 2], dtype=float32),
 array([1, 1, 1], dtype=float32),
 array(3, dtype=float32))

In [53]:
mx.sum(x * y)

array(3, dtype=float32)

In [54]:
A.shape, x.shape, mx.matmul(A, x), A@x

([2, 3], [3], array([5, 14], dtype=float32), array([5, 14], dtype=float32))

In [56]:
B = mx.ones((3, 4))
mx.matmul(A, B), A@B

(array([[3, 3, 3, 3],
        [12, 12, 12, 12]], dtype=float32),
 array([[3, 3, 3, 3],
        [12, 12, 12, 12]], dtype=float32))

In [58]:
u = mx.array([3.0, -4.0])
mx.linalg.norm(u)

array(5, dtype=float32)

In [59]:
mx.abs(u).sum()

array(7, dtype=float32)

In [60]:
mx.linalg.norm(mx.ones((4, 9)))

array(6, dtype=float32)